Re-enable windows for nym-vpn-core CI and release
nymtech/nym-vpn-client pull request #1401
Opened 2024-10-27 10:00 UTC by octol

2024-10-27 11:08 UTC, rokas-ambrazevicius approved these changes

2024-10-28 09:26 UTC, pronebird approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1401#-:-OAHRcaQ-J5xZv6855Vf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @octol)



<!-- Sent from Reviewable.io -->

2024-10-28 15:23 UTC, pronebird requested changes
Working on introducing msys2 that I know use to build wireguard-go

2024-10-29 06:56 UTC, pronebird commented
Main build is all green: https://github.com/nymtech/nym-vpn-client/actions/runs/11568586122/job/32201088230

2024-10-29 07:02 UTC, pronebird approved these changes

2024-10-29 07:25 UTC, octol commented on .github/workflows/ci-nym-vpn-core-windows.yml
> +          echo "RUSTFLAGS=-L ${GITHUB_WORKSPACE}/build/lib -Clink-args=/LIBPATH:${GITHUB_WORKSPACE}/build/lib/x64-Debug" >> $GITHUB_ENV
I thought we didn't need this anymore @pronebird ?

2024-10-29 07:26 UTC, octol commented on .github/workflows/ci-nym-vpn-core-windows.yml
> +          curl --output ${GITHUB_WORKSPACE}/winpcap.zip https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip
I think this one is unused, let me try removing it

2024-10-29 07:27 UTC, octol commented on .github/workflows/ci-nym-vpn-core-windows.yml
> +          echo "RUSTFLAGS=-L ${GITHUB_WORKSPACE}/build/lib -Clink-args=/LIBPATH:${GITHUB_WORKSPACE}/build/lib/x64-Debug" >> $GITHUB_ENV
oh I see now, it's for winfw et al

2024-10-29 07:52 UTC, merged

2024-10-29 08:17 UTC, pronebird reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1401)* status: 1 of 7 files reviewed, 1 unresolved discussion

___
*[`.github/workflows/ci-nym-vpn-core-windows.yml` line 45 at r8](https://reviewable.io/reviews/nymtech/nym-vpn-client/1401#gh-1820232534:-OAMLMsnC_zo1TEI3f9t:b-jpw8kf) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/d2ee1f40afca0c1f29c210e66cb21f823c0c6de5/.github/workflows/ci-nym-vpn-core-windows.yml#L45)):*
<details><summary><i>Previously, octol (Jon Häggblad) wrote…</i></summary><blockquote>

oh I see now, it's for winfw et al
</blockquote></details>

Yes. Some of the firewall libs are put in there. We don't really use firewall but I didn't want to remove these steps because soon we'll need them again.


<!-- Sent from Reviewable.io -->