Enable cover traffic for mobile
nymtech/nym-vpn-client pull request #1663
Opened 2024-11-26 18:21 UTC by neacsu

In order to not kill the whole tunnel on mobile platforms like Android because the mixnet channel auto-shuts down when the tcp connection is unused, we do the same thing as on mixnet mode i.e. enable cover traffic, which basically keeps the websocket active permanently. This is a temporary solution, until we have a better way to treat the machine going to sleep.

2024-11-26 18:22 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1663)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @doums, @neacsu, @octol, @rokas-ambrazevicius, and @zaneschepke)

___
*[`nym-vpn-core/crates/nym-vpn-lib/src/tunnel_state_machine/tunnel/mod.rs` line 161 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1663#-OCdhSAMDZZZNQaNjejx:-OCdhSAMDZZZNQaNjejy:blhrunt) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/3a70b3dd57514ced1e58340ec487fe81003b2053/nym-vpn-core/crates/nym-vpn-lib/src/tunnel_state_machine/tunnel/mod.rs#L161)):*
> ```XML
>             // Always disable poisson process for outbound traffic in wireguard.
>             mixnet_client_config.disable_poisson_rate = true;
>             // Always disable background cover traffic in wireguard.
> ```

Can you keep it but only for desktop platforms macos/windows/linux. and set it to false for android only?


<!-- Sent from Reviewable.io -->

2024-11-26 18:24 UTC, pronebird requested changes
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1663)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @doums, @neacsu, @octol, @rokas-ambrazevicius, and @zaneschepke)

___
*[`nym-vpn-core/crates/nym-vpn-lib/src/tunnel_state_machine/tunnel/mod.rs` line 161 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1663#-OCdhSAMDZZZNQaNjejx:-OCdhmSs3bfqBbtEVrU5:brc1beo) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/3a70b3dd57514ced1e58340ec487fe81003b2053/nym-vpn-core/crates/nym-vpn-lib/src/tunnel_state_machine/tunnel/mod.rs#L161)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

Can you keep it but only for desktop platforms macos/windows/linux. and set it to false for android only?
</blockquote></details>

oh: keep it true on ios because i don't think it matters for ios. It will sleep regardless.


<!-- Sent from Reviewable.io -->

2024-11-27 07:33 UTC, octol approved these changes
Consider lowering the rate from the default 20 sphinx packets/sec if it saves battery

2024-11-27 10:10 UTC, neacsu reviewed
> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1663)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @doums, @pronebird, @rokas-ambrazevicius, and @zaneschepke)

___
*[`nym-vpn-core/crates/nym-vpn-lib/src/tunnel_state_machine/tunnel/mod.rs` line 161 at r1](https://reviewable.io/reviews/nymtech/nym-vpn-client/1663#-OCdhSAMDZZZNQaNjejx:-OCh3EEaEo8OIpTOLOt0:b-gwyj2w) ([raw file](https://github.com/nymtech/nym-vpn-client/blob/3a70b3dd57514ced1e58340ec487fe81003b2053/nym-vpn-core/crates/nym-vpn-lib/src/tunnel_state_machine/tunnel/mod.rs#L161)):*
<details><summary><i>Previously, pronebird (Andrej Mihajlov) wrote…</i></summary><blockquote>

oh: keep it true on ios because i don't think it matters for ios. It will sleep regardless.
</blockquote></details>

For desktop platforms it is already disabled, when in two hop mode (https://github.com/nymtech/nym-vpn-client/blob/d3bafc5198761a12be6d7293b00a406995922e1a/nym-vpn-core/crates/nym-vpnd/src/command_interface/listener.rs#L930)
I've pushed a change to keep it disabled only for iOS, and on Android it will get enabled by default.


<!-- Sent from Reviewable.io -->

2024-11-27 10:30 UTC, neacsu reviewed
Changed it to 1 packet/10 seconds

> *[Reviewable](https://reviewable.io/reviews/nymtech/nym-vpn-client/1663#-:-OChA2IK6JXr5jYI6Mbz:bpa069h)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @doums, @pronebird, @rokas-ambrazevicius, and @zaneschepke)



<!-- Sent from Reviewable.io -->

2024-11-27 10:45 UTC, pronebird commented on nym-vpn-core/crates/nym-vpn-lib/src/mixnet/connect.rs
> +    if two_hop_mode && (cfg!(target_os = "android") || cfg!(target_os = "ios")) {
Nit: this will have no effect on ios as we disable cover traffic in there anyway. The thing is, ios tunnel doesn't care about cover traffic, it will suspend entirely whenever it wants to.

2024-11-27 11:20 UTC, zaneschepke approved these changes

2024-11-27 11:26 UTC, neacsu commented on nym-vpn-core/crates/nym-vpn-lib/src/mixnet/connect.rs
> +    if two_hop_mode && (cfg!(target_os = "android") || cfg!(target_os = "ios")) {
Yep, I know, it's just redundant code, just in case at some point it gets enabled, we have rare keep-alives there as well

2024-11-27 11:36 UTC, pronebird approved these changes

2024-11-27 11:44 UTC, merged