Add min gateway performance to probe
nymtech/nym-vpn-client pull request #1708
Opened 2024-12-03 12:46 UTC by neacsu

2024-12-03 12:58 UTC, jstuczyn approved these changes

2024-12-03 14:20 UTC, octol approved these changes

2024-12-04 08:58 UTC, jstuczyn requested changes
I think based on what @tommyv1987 has been saying, you might have to also add that optional performance to the debug section of the constructed mixnet client like I've attempted to do in this experiment: https://github.com/nymtech/nym-vpn-client/pull/1710

2024-12-04 11:08 UTC, tommyv1987 approved these changes

2024-12-04 12:04 UTC, jstuczyn approved these changes

2024-12-04 12:09 UTC, merged