Combine dependabot security updates
nymtech/nym-vpn-client pull request #1831
Opened 2024-12-20 15:39 UTC by jmwample

Several dependabot security warnings have been sitting, this PR combines them and works to integrate any necessary changes to address the security issues.

- [x] #1828 
- [x] #1782 
- [x] #1781 
- [x] #1745 
- [x] #1601 
- [x] #1600

2024-12-20 22:31 UTC, pronebird commented
Some of these are major updates. We might need to verify if things are still working as expected. 

Doing this in bulk across many apps could be problematic especially with a lot of people on holidays at the moment.

2024-12-20 22:37 UTC, jmwample commented
This is definitely true, I was playing with combining all of them to knock them out since many of them are not breaking changes and close significant bugs. However, I have discovered that dependabot suggesting to just do things like migrate to react v19 are much bigger changes. So I will likely leave that specifically out.

2024-12-20 22:37 UTC, jmwample commented
This is definitely true, I was playing with combining all of them to knock them out since many of them are not breaking changes and close significant bugs. However, I have discovered that dependabot suggesting to just do things like migrate to react v19 are much bigger changes. So I will likely leave that specifically out.

2024-12-20 22:49 UTC, zaneschepke commented
I'll need to test this on Android because a few of these packages broke android in the past when we upgraded

2024-12-20 22:50 UTC, pronebird commented
This one is no longer applicable

https://github.com/nymtech/nym-vpn-client/pull/1601

2024-12-20 23:04 UTC, jmwample commented
> I'll need to test this on Android

Noted. I am not trying to merge this immediately and shake things up on Friday evening before holidays, just do some house cleaning while I have the time :smile:

2024-12-20 23:05 UTC, pronebird approved these changes
Looks sane 👍

2024-12-21 10:42 UTC, pronebird requested changes

2024-12-21 10:42 UTC, pronebird commented on nym-vpn-core/crates/nym-vpnc/Cargo.toml
> +[target.'cfg(windows)'.dependencies]
Neither of these crates seem to be used in `nym-vpnc` based on a quick search with Github

2024-12-21 10:43 UTC, pronebird commented on nym-vpn-core/crates/nym-vpnd/Cargo.toml
> +winapi = { version = "0.3", features = ["winnt", "excpt", "winerror"] }
FYI Not a problem with this PR but to raise awareness. We've been putting effort at consolidating dependencies in the workspace Cargo.toml so it's easier to keep track of them. IMO features can be specified by each indiviudal crate, that's ok.

2025-01-02 16:02 UTC, jmwample commented on nym-vpn-core/crates/nym-vpnc/Cargo.toml
> +[target.'cfg(windows)'.dependencies]
I removed the extra imports, we really only needed the winapi feature. We don't even directly use this, this fixes an issue in the (unmaintained) package `parity-tokio-ipc` which breaks when built against the latest winapi without the `winerror` feature enabled.

I am actually not sure the equivalent of this import can even be achieved in the workspace `Cargo.toml` because this is a transitive dependency.

2025-01-02 16:03 UTC, jmwample commented on nym-vpn-core/crates/nym-vpnd/Cargo.toml
> +winapi = { version = "0.3", features = ["winnt", "excpt", "winerror"] }
I am actually not sure the equivalent of this import can even be achieved in the workspace `Cargo.toml` because this is a transitive dependency.

2025-01-02 16:06 UTC, jmwample commented
I believe this is ready to be merged. The issues in the android build are between `nym-vpn-android`  and our generated uniffi interface unrelated to any of the changes in this PR.

2025-01-02 16:10 UTC, jmwample commented
Just to have this as a note here, I held back `rust2go` at `v0.3.16` because allowing the update to latest (`v0.3.17`) breaks windows build with an error relating to linker flags in the generated C ffi code connecting go and rust.

2025-01-03 18:23 UTC, pronebird approved these changes
Let's go! 🚀

2025-01-03 18:23 UTC, merged